# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0fcb33c5f4f8f51f9c0a36c2be8f96cc39117dc393805977d91d42cbbd97ebf343e897b69393420e2fc5f47f22f2b8504f5175748be56389fed3a49e11f979a

test:
  secret_key_base: 6d0dcb1ae6e0f6b258be0f613315fc7977329b07f1cba3904d4116ae1defe2248b4a7289770b3156531ec54085db0b7959238a3c57f976645bf3ad7ccd04fe3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
